### ISSUE TITLE
Jetpack still inverts when double-clicking

### ISSUE THREAD

**Issue by a1russell** [echoman-dev/Uninvertible-Jetpack#1]
In addition to dropping the jetpack while holding the mouse button to cause the invert bug, which this mod fixes, it is also possible to invert the jetpack by double-clicking the mouse. Currently this mod does not solve the latter issue. Would it be possible to also fix this?

**Comment by echoman-dev** [comment]
> In addition to dropping the jetpack while holding the mouse button to cause the invert bug, which this mod fixes, it is also possible to invert the jetpack by double-clicking the mouse. Currently this mod does not solve the latter issue. Would it be possible to also fix this?

I was unaware of the double click method for inverting.

If it doesn't get a PR by the time I have the time sufficient to get to the bottom of it, which is likely, I'll look into it.

Thank you very much for taking the time to open the issue.

**Comment by echoman-dev** [comment]
I had a free hour to look into it.

Only managed to create a crude fix: **the jetpack no longer inverts**, but the activation and deactivation effects will play if you try to invert, keep holding the button, then release. I tried simple fixes to patch this out as well, those all failed and I don't have enough time to sink into it sadly.

**Comment by echoman-dev** [comment]
The new version is now available on thunderstore. Thank you again for bringing up the issue

**Comment by a1russell** [comment]
You're welcome, and thank you as well!
